# Site settings
title:          THE REMAINS
description:    "A place to record my story"
url:            "https://the-remains.github.io"

# Google Analytics
google_analytics: UA-228687365-1

# Author
author:
  name:         Donald
  url:          https://the-remains.github.io
  email:        srioa@pm.me

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       8

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Giscus
giscus:
  repo: 'the-remains/comments'
  repo_id: 'R_kgDOHj-n9Q'
  category: 'General'
  category_id: 'DIC_kwDOHj-n9c4CP4kt'
  mapping: 'pathname'
  input_position: 'top'
  theme: 'light'
  lang: "en"